module.exports = {
    EMPLOYEE_SEARCH: 'EMPLOYEE_SEARCH',
    EMPLOYEE_PAGING: 'EMPLOYEE_PAGING',
    EMPLOYEE_SORTING: 'EMPLOYEE_SORTING',
    EMPLOYEE_CHANGE_ITEM_PER_PAGE: 'EMPLOYEE_CHANGE_ITEM_PER_PAGE',
    EMPLOYEE_EDIT: 'EMPLOYEE_EDIT',
    EMPLOYEE_CANCEL: 'EMPLOYEE_CANCEL',
    EMPLOYEE_SAVE: 'EMPLOYEE_SAVE',
    EMPLOYEE_CONFIRM_DELETE: 'EMPLOYEE_CONFIRM_DELETE',
    EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
    DATE_FORMAT: 'DD/MM/YYYY',
    URL: 'http://localhost:1234/',
    URL_RESOURCE: 'http://localhost:1234/Resources/Images/'
};